# Generated by Django 3.2.6 on 2021-10-26 14:42

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giaohang', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='danhgiashipper',
            name='shipper',
        ),
        migrations.RemoveField(
            model_name='danhgiashipper',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hoadon',
            name='dau_gia_duoc_chon',
        ),
        migrations.RemoveField(
            model_name='hoadon',
            name='hoan_thanh',
        ),
        migrations.RemoveField(
            model_name='hoadon',
            name='shipper',
        ),
        migrations.RemoveField(
            model_name='hoadon',
            name='user',
        ),
        migrations.AlterField(
            model_name='danhgiashipper',
            name='hoa_don',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='danh_gia', to='giaohang.hoadon'),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='giam_gia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khuyen_mai', to='giaohang.khuyenmai'),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='tong_gia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.CreateModel(
            name='DonHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=True)),
                ('hoan_thanh', models.BooleanField(default=False)),
                ('dau_gia_duoc_chon', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bai_dang_hoa_don', to='giaohang.daugia')),
                ('shipper', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipper', to='giaohang.shipper')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='hoadon',
            name='don_hang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='hoa_don', to='giaohang.donhang'),
        ),
    ]
