# Generated by Django 3.2.6 on 2021-10-26 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giaohang', '0002_auto_20211026_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='donhang',
            name='bai_dang',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_hang', to='giaohang.baidang'),
        ),
        migrations.AlterField(
            model_name='donhang',
            name='dau_gia_duoc_chon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_hang', to='giaohang.daugia'),
        ),
    ]
