# Generated by Django 3.2.6 on 2021-10-28 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giaohang', '0003_auto_20211027_0634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hoadon',
            name='giam_gia',
        ),
        migrations.AddField(
            model_name='donhang',
            name='giam_gia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='khuyen_mai', to='giaohang.khuyenmai'),
        ),
    ]
