# Generated by Django 3.2.6 on 2021-11-05 11:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('giaohang', '0004_auto_20211029_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donhang',
            name='shipper',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='don_hang', to='giaohang.shipper'),
        ),
    ]
