# Generated by Django 3.2.6 on 2021-11-05 15:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('giaohang', '0005_alter_donhang_shipper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daugia',
            name='gia_giao_hang_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='hoadon',
            name='tong_gia',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
